/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type InventoryConfig struct {
	// Soft limit on number of compute managers, which can be added, beyond which, addition of compute managers will result in warning getting logged 
	ComputeManagersSoftLimit int32 `json:"compute_managers_soft_limit"`
}
