/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PrefixConfig struct {
	// Action for the IPPrefix
	Action string `json:"action"`
	// Greater than or equal to
	Ge int64 `json:"ge,omitempty"`
	// Less than or equal to
	Le int64 `json:"le,omitempty"`
	// If absent, the action applies to all addresses.
	Network string `json:"network,omitempty"`
}
