/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MigrationUnitAggregateInfo struct {
	// Link to this resource
	Self *SelfResourceLink `json:"_self,omitempty"`
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	// Status of migration unit
	Status string `json:"status,omitempty"`
	// Indicator of migration progress in percentage
	PercentComplete float32 `json:"percent_complete,omitempty"`
	// List of errors occurred during migration of this migration unit
	Errors []string `json:"errors,omitempty"`
	// Details of the migration unit
	Unit *MigrationUnit `json:"unit,omitempty"`
}
