/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// The load balancer node usage summary for all nodes. Only EdgeNode is supported. The summary calculation is based on all edge nodes configured in edge clusters. 
type LbNodeUsageSummary struct {
	// The overall usage percentage of all nodes for the load balancer services. 
	UsagePercentage float32 `json:"usage_percentage,omitempty"`
	// The current credit number reflects the overall credit usage for all nodes. 
	CurrentCreditNumber int64 `json:"current_credit_number,omitempty"`
	// The property contains lb node usages for each node. 
	NodeUsages []LbNodeUsage `json:"node_usages,omitempty"`
	// The severity calculation is based on current credit usage percentage of load balancer for all nodes. 
	Severity string `json:"severity,omitempty"`
	// The property identifies array of node count for each severity (RED, ORANGE and GREEN). 
	NodeCounts []LbNodeCountPerSeverity `json:"node_counts,omitempty"`
	// The remaining credit number is the overall remaining credits that can be used for load balancer service configuration for all nodes. 
	RemainingCreditNumber int64 `json:"remaining_credit_number,omitempty"`
}
