/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Host Switch specification
type HostSwitch struct {
	// Physical NICs connected to the host switch
	Pnics []Pnic `json:"pnics,omitempty"`
	// If this name is unset or empty then the default host switch name will be used. The name must be unique among all host switches specified in a given Transport Node; unset name, empty name and the default host switch name are considered the same in terms of uniqueness.
	HostSwitchName string `json:"host_switch_name,omitempty"`
	// ID of configured Static IP Pool. If specified allocate IP for Endpoints from Pool. Else assume IP will be assigned for Endpoints from DHCP. This field is deprecated, use ip_assignment_spec field instead.
	StaticIpPoolId string `json:"static_ip_pool_id,omitempty"`
	// HostSwitch profiles bound to this HostSwitch. If a profile ID is not provided for any HostSwitchProfileType that is supported by the Transport Node, the corresponding default profile will be bound to the HostSwitch.
	HostSwitchProfileIds []HostSwitchProfileTypeIdEntry `json:"host_switch_profile_ids,omitempty"`
}
