/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// A single respose in a list of batched responses
type BatchResponseItem struct {
	// object returned by api
	Body *interface{} `json:"body,omitempty"`
	// The headers returned by the API call
	Headers *interface{} `json:"headers,omitempty"`
	// http status code
	Code int64 `json:"code"`
}
