/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AddControllerNodeSpec struct {
	MpaMsgClientInfo *MsgClientInfo `json:"mpa_msg_client_info"`
	HostMsgClientInfo *MsgClientInfo `json:"host_msg_client_info"`
	// The details of the controller node required for cluster initialization or joining to an existing cluster.  If this property is set, the node will be added to an existing cluster or used to create a new cluster.  Otherwise no clustering operation/s will be performed.
	ClusteringParams *ClusteringInfo `json:"clustering_params,omitempty"`
	// Only use this if an id for the node already exists with MP. If not specified, then the node_id will be set to a random id.
	NodeId string `json:"node_id,omitempty"`
	// Deprecated. Do not supply a value for this property.
	ControlPlaneServerCertificate string `json:"control_plane_server_certificate,omitempty"`
	// must be set to AddControllerNodeSpec
	Type_ string `json:"type"`
}
