/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SSH Service properties
type SshServiceProperties struct {
	// Start service when system boots
	StartOnBoot bool `json:"start_on_boot"`
}
