/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// A shaper configuration entry that specifies type and metrics
type QosBaseRateShaper struct {
	Enabled bool `json:"enabled"`
	ResourceType string `json:"resource_type"`
}
