/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type BgpRouteAggregation struct {
	// Flag to send only summarized route
	SummaryOnly bool `json:"summary_only,omitempty"`
	// cidr of the aggregate address
	Prefix string `json:"prefix"`
}
