/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Describes status of configuration of an entity
type ConfigurationStateElement struct {
	// URI of backing resource on sub system
	SubSystemAddress string `json:"sub_system_address,omitempty"`
	// State of configuration on this sub system
	State string `json:"state,omitempty"`
	// Type of backing resource on sub system
	SubSystemType string `json:"sub_system_type,omitempty"`
	// Error message in case of failure
	FailureMessage string `json:"failure_message,omitempty"`
	// Error code
	FailureCode int64 `json:"failure_code,omitempty"`
	// Identifier of backing resource on sub system
	SubSystemId string `json:"sub_system_id,omitempty"`
}
