/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IKE session traffic summary provides IKE session status and aggregate of traffic across all tunnel.
type IpSecVpnSessionStatus struct {
	// UUID of vpn session.
	IpsecVpnSessionId string `json:"ipsec_vpn_session_id,omitempty"`
	// Display name of vpn session.
	DisplayName string `json:"display_name,omitempty"`
	// Number of failed tunnels.
	FailedTunnels int64 `json:"failed_tunnels,omitempty"`
	// Number of negotiated tunnels.
	NegotiatedTunnels int64 `json:"negotiated_tunnels,omitempty"`
	// Gives session status consolidated using IKE status and tunnel status. It can be UP, DOWN, DEGRADED. If IKE and all tunnels are UP status will be UP, if all down it will be DOWN, otherwise it will be DEGRADED.
	SessionStatus string `json:"session_status,omitempty"`
	// Timestamp when the data was last updated.
	LastUpdateTimestamp int64 `json:"last_update_timestamp,omitempty"`
	// Aggregate traffic statistics across all ipsec tunnels.
	AggregateTrafficCounters *IpSecVpnTrafficCounters `json:"aggregate_traffic_counters,omitempty"`
	// Status for IPSec VPN IKE session UP/DOWN and fail reason if IKE session is down.
	IkeStatus *IpSecVpnikeSessionStatus `json:"ike_status,omitempty"`
	// Total number of tunnels.
	TotalTunnels int64 `json:"total_tunnels,omitempty"`
}
