/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Section query parameters
type DsSectionQueryParameters struct {
	// Flag to cascade delete of this object to all it's child objects.
	Cascade bool `json:"cascade,omitempty"`
}
