/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Duplicate IP detection and control
type DuplicateIpDetection struct {
	// Indicates whether duplicate IP detection should be enabled
	DuplicateIpDetectionEnabled bool `json:"duplicate_ip_detection_enabled,omitempty"`
}
