/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MetadataProxyStatistics struct {
	// timestamp of the statistics
	Timestamp int64 `json:"timestamp"`
	// metadata proxy statistics per logical switch
	Statistics []MetadataProxyStatisticsPerLogicalSwitch `json:"statistics,omitempty"`
	// metadata proxy uuid
	MetadataProxyId string `json:"metadata_proxy_id"`
}
