/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type StatusCount struct {
	// Roll-up status
	Status string `json:"status,omitempty"`
	// Degraded count
	DegradedCount int32 `json:"degraded_count,omitempty"`
	// Down count
	DownCount int32 `json:"down_count,omitempty"`
	// Up count
	UpCount int32 `json:"up_count,omitempty"`
}
