/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type L2VpnAttachmentContext struct {
	// A flag to indicate whether to allocate addresses from allocation     pools bound to the parent logical switch. 
	AllocateAddresses string `json:"allocate_addresses,omitempty"`
	// Used to identify which concrete class it is
	ResourceType string `json:"resource_type"`
	// Tunnel Id to uniquely identify the extension.
	TunnelId int32 `json:"tunnel_id"`
}
