/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Details of Container Ingress Policy.
type ContainerIngressPolicy struct {
	// Link to this resource
	Self *SelfResourceLink `json:"_self,omitempty"`
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	// Timestamp of last modification
	LastSyncTime int64 `json:"_last_sync_time,omitempty"`
	// Defaults to ID if not set
	DisplayName string `json:"display_name,omitempty"`
	// Description of this resource
	Description string `json:"description,omitempty"`
	// The type of this resource.
	ResourceType string `json:"resource_type"`
	// Opaque identifiers meaningful to the API user
	Tags []Tag `json:"tags,omitempty"`
	// Identifier of the container cluster this ingress policy belongs to.
	ContainerClusterId string `json:"container_cluster_id,omitempty"`
	// Array of additional specific properties of container ingress in key-value format. 
	OriginProperties []KeyValuePair `json:"origin_properties,omitempty"`
	// Identifier of the container ingress policy.
	ExternalId string `json:"external_id"`
	// Identifier of the project which this container ingress belongs to.
	ContainerProjectId string `json:"container_project_id,omitempty"`
	// Container ingress policy specification.
	Spec string `json:"spec,omitempty"`
}
