/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Attribute specific to a partner. There attributes are passed on to the partner appliance and is opaque to the NSX Manager. The Attributes used by the partner applicance.
type Attribute struct {
	// Read only Attribute cannot be overdidden by service instance/deployment.
	ReadOnly bool `json:"read_only,omitempty"`
	// Attribute Type can be of any of the allowed enum type.
	AttributeType string `json:"attribute_type,omitempty"`
	// Attribute display name string value.
	DisplayName string `json:"display_name,omitempty"`
	// Attribute value string value.
	Value string `json:"value,omitempty"`
	// Attribute key string value.
	Key string `json:"key"`
}
