/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// pNIC/bond statuses
type PnicBondStatus struct {
	// Status of pNIC/bond
	Status string `json:"status,omitempty"`
	// type, whether the object is a pNIC or a bond
	Type_ string `json:"type,omitempty"`
	// Name of the pNIC/bond
	Name string `json:"name,omitempty"`
}
