/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IPSec VPN session traffic summary.
type IpSecVpnSessionTrafficSummary struct {
	// Traffic stastics.
	TrafficCounters *IpSecVpnTrafficCounters `json:"traffic_counters,omitempty"`
	// VPN Session.
	IpsecVpnSession *ResourceReference `json:"ipsec_vpn_session,omitempty"`
}
