/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// An address binding entry is a combination of the IP-MAC-VLAN binding for a logical port. The address bindings can be obtained via various methods like ARP snooping, DHCP snooping etc. or by user configuration. 
type AddressBindingEntry struct {
	// Source from which the address binding entry was obtained
	Source string `json:"source,omitempty"`
	// Combination of IP-MAC-VLAN binding
	Binding *PacketAddressClassifier `json:"binding,omitempty"`
	// Timestamp at which the binding was discovered via snooping or manually specified by the user 
	BindingTimestamp int64 `json:"binding_timestamp,omitempty"`
}
