/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Abstract base type for specification of IPs to be used with host switch virtual tunnel endpoints
type IpAssignmentSpec struct {
	ResourceType string `json:"resource_type"`
}
