/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Provides IPSec VPN session status.
type IpSecVpnTransportStatus struct {
	// Resource types of L2VPN Transport tunnels
	ResourceType string `json:"resource_type"`
	// Transport tunnel id.
	TunnelId *ResourceReference `json:"tunnel_id,omitempty"`
	// VPN session status provides IKE session status and aggregate of traffic across all tunnel.
	Status *IpSecVpnSessionStatus `json:"status,omitempty"`
}
