/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Node AAA provider vIDM status
type NodeAuthProviderVidmStatus struct {
	// AAA provider vIDM status
	RuntimeState string `json:"runtime_state"`
	// vIDM enable flag
	VidmEnable bool `json:"vidm_enable"`
}
