/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Vidm Info
type VidmInfo struct {
	// User's Full Name Or User Group's Display Name
	DisplayName string `json:"display_name,omitempty"`
	// Type
	Type_ string `json:"type,omitempty"`
	// Username Or Groupname
	Name string `json:"name,omitempty"`
}
