/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LogicalSwitchStatusSummary struct {
	// Timestamp when the data was last updated; unset if data source has never updated the data.
	LastUpdateTimestamp int64 `json:"last_update_timestamp,omitempty"`
	// The total number of logical switches.
	TotalSwitches int64 `json:"total_switches"`
	// The filters used to find the logical switches- TransportZone id, LogicalSwitchProfile id or TransportType
	Filters []Filter `json:"filters,omitempty"`
	// The number of logical switches that are realized in all transport nodes.
	FullyRealizedSwitches int64 `json:"fully_realized_switches"`
}
