/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Parameters to start an application discovery session. It can have NSGroup Ids as well as the App Profile Ids. 
type StartAppDiscoverySessionParameters struct {
	// NSGroup Ids
	NsGroupIds []string `json:"ns_group_ids"`
	// App Profile Ids
	AppProfileIds []string `json:"app_profile_ids,omitempty"`
}
