/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BGP Graceful Restart configuration parameters
type GracefulRestartConfig struct {
	// BGP Graceful Restart mode
	GracefulRestartMode string `json:"graceful_restart_mode,omitempty"`
	// Graceful Restart timers configuration
	GracefulRestartTimer *GracefulRestartTimer `json:"graceful_restart_timer,omitempty"`
}
