/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IP and MAC pair.
type IpMacPair struct {
	// IP address
	Ip string `json:"ip"`
	// MAC address
	Mac string `json:"mac,omitempty"`
}
