/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Note- transport node templates APIs are deprecated and user is recommended to use transport node profiles APIs instead.
type TransportNodeTemplateState struct {
	// Transport node template state on individual hosts of ComputeCollection which enabled automated transport code creation. 'FAILED_TO_CREATE' means transport node isn't created. 'IN_PROGRESS' means transport node is in progress of creation. 'FAILED_TO_REALIZE' means transport node has been created, but failed on host realization, it will repush to host by NSX later. 'SUCCESS' means transport node creation is succeeded. 
	State string `json:"state,omitempty"`
	// node id
	NodeId string `json:"node_id"`
	// transport node id
	TransportNodeId string `json:"transport_node_id,omitempty"`
}
