/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Holds status of target resource in firewall context.
type TargetResourceStatus struct {
	// Firewall status on a target logical resource.
	TargetStatus string `json:"target_status"`
	// Identifier of the NSX resource.
	TargetId string `json:"target_id,omitempty"`
}
