/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Tunnel endpoint configuration of preconfigured host switch
type PreconfiguredEndpoint struct {
	// Name of the virtual tunnel endpoint
	DeviceName string `json:"device_name"`
}
