/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Overall restore process status
type GlobalRestoreStatus struct {
	// A description of the restore status
	Description string `json:"description,omitempty"`
	// Global rolled-up restore status value
	Value string `json:"value,omitempty"`
}
