/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Type of issue and detailed description of the issues in case of post-VM  deployment configuration failure.
type SvmConfigureIssue struct {
	// List of errors along with details like errorId and error messages.
	Errors []SiErrorClass `json:"errors,omitempty"`
	// The ID of service instance which was deployed.
	ServiceInstanceId string `json:"service_instance_id,omitempty"`
}
