/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DHCP classless static route option.
type ClasslessStaticRoute struct {
	// IP address of next hop of the route.
	NextHop string `json:"next_hop"`
	// Destination network in CIDR format.
	Network string `json:"network"`
}
