/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// HealthCheckSpecVlan is used for specifying VLAN ID ranges for healthcheck. 
type HealthCheckSpecVlans struct {
	// VLAN ID ranges
	VlanRanges []HealthCheckVlanRange `json:"vlan_ranges"`
}
