/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Meta-data of pre/post-upgrade checks for a component
type ComponentUpgradeChecksInfo struct {
	// Collection of pre-upgrade checks
	PreUpgradeChecksInfo []UpgradeCheckInfo `json:"pre_upgrade_checks_info,omitempty"`
	// Collection of post-upgrade checks
	PostUpgradeChecksInfo []UpgradeCheckInfo `json:"post_upgrade_checks_info,omitempty"`
	// Component type of the pre/post-upgrade checks
	ComponentType string `json:"component_type"`
}
