/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Object to identify an uplink based on its type and name
type Uplink struct {
	// Name of this uplink
	UplinkName string `json:"uplink_name"`
	// Type of the uplink
	UplinkType string `json:"uplink_type"`
}
