/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IPv4 address properties
type IPv4AddressProperties struct {
	// Interface netmask
	Netmask string `json:"netmask,omitempty"`
	// Interface IPv4 address
	IpAddress string `json:"ip_address,omitempty"`
}
