/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Remote MAC addresses for logical switch.
type L2VpnSessionRemoteMacsForLs struct {
	// Mac addresses.
	RemoteMacAddresses []string `json:"remote_mac_addresses,omitempty"`
	// Logical switch.
	LogicalSwitch *ResourceReference `json:"logical_switch,omitempty"`
}
