/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SNMP Service properties
type SnmpServiceProperties struct {
	// SNMP v1, v2c community
	Communities []string `json:"communities,omitempty"`
	// Start when system boots
	StartOnBoot bool `json:"start_on_boot"`
}
