/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Entity lists where the profile will be enabled on. 
type AppliedTos struct {
	// Logical Port List
	LogicalPorts []ResourceReference `json:"logical_ports,omitempty"`
	// Logical Switch List
	LogicalSwitches []ResourceReference `json:"logical_switches,omitempty"`
	// NSGroup List
	Nsgroups []ResourceReference `json:"nsgroups,omitempty"`
}
