/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Possible values of a mode in a \"/config/nsx_appliance_mode\" file
type NodeMode struct {
	// Possible enum values in a \"/config/nsx_appliance_mode\" file
	ModeId string `json:"mode_id"`
}
