/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ControllerClusterRoleConfig struct {
	// Type of this role configuration
	Type_ string `json:"type,omitempty"`
	MpaMsgClientInfo *MsgClientInfo `json:"mpa_msg_client_info,omitempty"`
	HostMsgClientInfo *MsgClientInfo `json:"host_msg_client_info,omitempty"`
	// The IP and port for the control plane service on this node
	ControlPlaneListenAddr *ServiceEndpoint `json:"control_plane_listen_addr,omitempty"`
	// The IP and port for the control cluster service on this node
	ControlClusterListenAddr *ServiceEndpoint `json:"control_cluster_listen_addr,omitempty"`
}
