/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// install-upgrade service properties
type InstallUpgradeServiceProperties struct {
	// IP of manager on which install-upgrade is enabled
	EnabledOn string `json:"enabled_on,omitempty"`
	// True if service enabled; otherwise, false
	Enabled bool `json:"enabled"`
}
