/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Runtime status information of the compute manager
type ComputeManagerStatus struct {
	// Version of the compute manager
	Version string `json:"version,omitempty"`
	// Status of connection with the compute manager
	ConnectionStatus string `json:"connection_status,omitempty"`
	// Errors when connecting with compute manager
	ConnectionErrors []ErrorInfo `json:"connection_errors,omitempty"`
	// Timestamp of the last successful update of Inventory, in epoch milliseconds.
	LastSyncTime int64 `json:"last_sync_time,omitempty"`
	// Details about connection status
	ConnectionStatusDetails string `json:"connection_status_details,omitempty"`
	// Errors when registering with compute manager
	RegistrationErrors []ErrorInfo `json:"registration_errors,omitempty"`
	// Registration status of compute manager
	RegistrationStatus string `json:"registration_status,omitempty"`
}
