/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Check to identify potential pre/post-upgrade issues
type UpgradeCheck struct {
	// Status of pre/post-upgrade check
	Status string `json:"status,omitempty"`
	// Name of the pre/post-upgrade check
	DisplayName string `json:"display_name,omitempty"`
	// List of failure messages
	FailureMessages []string `json:"failure_messages,omitempty"`
	// Component type
	ComponentType string `json:"component_type"`
}
