/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type TransportProtocolHeader struct {
	// UDP header
	UdpHeader *UdpHeader `json:"udp_header,omitempty"`
	// DHCP header
	DhcpHeader *DhcpHeader `json:"dhcp_header,omitempty"`
	// TCP header
	TcpHeader *TcpHeader `json:"tcp_header,omitempty"`
	// ICMP echo request header
	IcmpEchoRequestHeader *IcmpEchoRequestHeader `json:"icmp_echo_request_header,omitempty"`
	// DHCP v6 header
	Dhcpv6Header *Dhcpv6Header `json:"dhcpv6_header,omitempty"`
	// Neighbor discovery protocol header
	NdpHeader *NdpHeader `json:"ndp_header,omitempty"`
	// DNS header
	DnsHeader *DnsHeader `json:"dns_header,omitempty"`
}
