/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Clustering parameters for the controller cluster
type ClusteringInfo struct {
	// Shared secret of the cluster.
	SharedSecret string `json:"shared_secret,omitempty"`
	// Property to indicate if the node must join an existing cluster.
	JoinToExistingCluster bool `json:"join_to_existing_cluster"`
}
