/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IP Tunnel port configuration.
type TunnelPortConfig struct {
	// IP Tunnel port  (commonly referred as VTI) subnet.
	IpSubnets []IpSubnet `json:"ip_subnets"`
	// Logical route port identifier.
	TunnelPortId string `json:"tunnel_port_id,omitempty"`
}
