/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type RouteMapSequence struct {
	// Set Criteria for the RouteMap Sequence
	SetCriteria *RouteMapSequenceSet `json:"set_criteria,omitempty"`
	// Action for the Sequence
	Action string `json:"action"`
	// Match Criteria for the RouteMap Sequence
	MatchCriteria *RouteMapSequenceMatch `json:"match_criteria"`
}
