/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// L4PortSet can be specified in comma separated notation of parts. Parts of a L4PortSet includes single integer or range of port in hyphen notation. Example of a PortSet: \"22, 33-70, 44\". 
type L4PortSetNsService struct {
	// The specific type of NSServiceElement
	ResourceType string `json:"resource_type"`
	// Destination ports
	DestinationPorts []string `json:"destination_ports,omitempty"`
	L4Protocol string `json:"l4_protocol"`
	// Source ports
	SourcePorts []string `json:"source_ports,omitempty"`
}
