/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type TraceflowRequest struct {
	// Packet configuration
	Packet *PacketData `json:"packet"`
	// Maximum time (in ms) the management plane will wait for observation result list to be sent by controller plane.
	Timeout int64 `json:"timeout,omitempty"`
	// id of the source logical port to inject the traceflow packet into
	LportId string `json:"lport_id"`
}
