/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// An NSService element that represents an IP protocol
type IpProtocolNsService struct {
	// The specific type of NSServiceElement
	ResourceType string `json:"resource_type"`
	// The IP protocol number
	ProtocolNumber int64 `json:"protocol_number"`
}
