/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Remote file server
type RemoteFileServer struct {
	// Remote server directory to copy bundle files to
	DirectoryPath string `json:"directory_path"`
	// Protocol to use to copy file
	Protocol *FileTransferProtocol `json:"protocol"`
	// Server port
	Port int64 `json:"port,omitempty"`
	// Remote server hostname or IP address
	Server string `json:"server"`
}
