/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type NodeIdServicesMap struct {
	// list of ServiceTypes
	ServiceTypes []string `json:"service_types"`
	// NodeId
	NodeId string `json:"node_id"`
}
