/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ControllerClusterStatus struct {
	// The current status of the controller cluster
	Status string `json:"status,omitempty"`
}
