/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// An instance of service chain that consists of forward and reverse service paths.
type ServicePath struct {
	// Reverse service path if available that applies to egress traffic.
	ReversePath *UnidirectionalServicePath `json:"reverse_path,omitempty"`
	// Uuid of a service chain.
	ServiceChainUuid string `json:"service_chain_uuid,omitempty"`
	// Forward service path if available that applies to ingress traffic.
	ForwardPath *UnidirectionalServicePath `json:"forward_path,omitempty"`
	// Unique identifier of a service path.
	ServicePathId int64 `json:"service_path_id,omitempty"`
	// A unique id of a service chain.
	ServiceChainId int64 `json:"service_chain_id,omitempty"`
}
