/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Node network interface properties
type NodeInterfaceProperties struct {
	// Indicates whether interface is managed by the host
	HostManaged bool `json:"host_managed,omitempty"`
	// Interface administration status
	LinkStatus string `json:"link_status,omitempty"`
	// Indicates whether interface is enabled for Enhanced Networking Stack
	EnsEnabled bool `json:"ens_enabled,omitempty"`
	// Interface Type
	InterfaceType string `json:"interface_type,omitempty"`
	// Connected switch
	ConnectedSwitch string `json:"connected_switch,omitempty"`
	// Interface MTU
	Mtu int64 `json:"mtu,omitempty"`
	// Source of status data
	Source string `json:"source,omitempty"`
	// Interface administration status
	AdminStatus string `json:"admin_status,omitempty"`
	// Indicates whether backing of VIRTUAL network interface is managed by NSX
	BackingNsxManaged bool `json:"backing_nsx_managed,omitempty"`
	// LPort Attachment Id assigned to VIRTUAL network interface of a node
	LportAttachmentId string `json:"lport_attachment_id,omitempty"`
	// Interface ID
	InterfaceId string `json:"interface_id,omitempty"`
	// Interface capability for Enhanced Networking Stack
	EnsCapable bool `json:"ens_capable,omitempty"`
	// IP Alias
	InterfaceAlias []NodeInterfaceAlias `json:"interface_alias,omitempty"`
}
