/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Contains up-to-date information relating to an auto-deployed VM, including its status and (potentially) an error message. 
type IntelligenceClusterNodeVmDeploymentStatusReport struct {
	// Status of the addition or deletion of an auto-deployed NSX-Intelligence cluster node VM. 
	Status string `json:"status"`
	// In case of auto-deployment-related failure, an error message will be stored here. 
	FailureMessage string `json:"failure_message,omitempty"`
	// In case of auto-deployment-related failure, the code for the error will be stored here. 
	FailureCode int64 `json:"failure_code,omitempty"`
}
