/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Identity Firewall user login/session data for a single VM
type IdfwVmDetail struct {
	// Virtual machine (external ID or BIOS UUID) where login/logout event occurred.
	VmExtId string `json:"vm_ext_id"`
	// List of client machine IP addresses.
	VmIpAddresses []string `json:"vm_ip_addresses,omitempty"`
	// Record of the last logged in user session (if exists).
	LastLoginUserSession *ResourceReference `json:"last_login_user_session,omitempty"`
	// List of user session data.
	UserSessions []IdfwUserSessionData `json:"user_sessions"`
}
