/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Service properties
type LoggingServiceProperties struct {
	// Package logging levels
	PackageLoggingLevel []PackageLoggingLevels `json:"package_logging_level,omitempty"`
	// Service logging level
	LoggingLevel string `json:"logging_level"`
}
