/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PnicMirrorDestination struct {
	// Resource types of mirror destination
	ResourceType string `json:"resource_type"`
	// Physical NIC device names to which to send the mirrored packets
	DestPnics []string `json:"dest_pnics"`
	// Transport node to which to send the mirrored packets
	NodeId string `json:"node_id"`
}
