/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ServiceRouterAllocationConfig struct {
	// For TIER 1 logical router, for manual placement of service router within the cluster, edge cluster member indices needs to be provided else same will be auto-allocated. You can provide maximum two indices for HA ACTIVE_STANDBY. 
	EdgeClusterMemberIndices []int64 `json:"edge_cluster_member_indices,omitempty"`
	// Logical router allocation can be tracked for specific services and services may have their own hard limits and allocation sizes. For example load balancer pool should be specified if load balancer service will be attached to logical router. 
	AllocationPool *EdgeClusterMemberAllocationPool `json:"allocation_pool,omitempty"`
	// To reallocate TIER1 logical router on new or existing edge cluster 
	EdgeClusterId string `json:"edge_cluster_id"`
}
