/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LbVirtualServerWithRule struct {
	// It is used to add rules, update rules and bind rules to the virtual server. To add new rules, make sure that the rules have no identifier specified, the new rules are automatically generated and associated to the virtual server. If the virtual server need to consume some existed rules without change, those rules should not be specified in the list, otherwise, the rules are updated. For update_with_rules action, it supports rules delete and update. To delete old rules, the rules should not be configured in new action, the UUID of deleted rules should be removed from rule_ids. To update rules, the rules should be specified with new change and configured with identifier. If there are some rules which are not modified, those rule should not be specified in the rules list, the UUID list of rules should be specified in rule_ids of LbVirtualServer. 
	Rules []LbRule `json:"rules,omitempty"`
	// If rules need to be associated to the virtual server, please set rules properties of LbVirtualServerWithRule with rule list configuration. For the rules which are not modified but associated to the virtual server, the rule UUID list should be specified in rule_ids property of LbVirtualServer and the associated rules should not be specified in rules of LbVirtualServerWithRule. 
	VirtualServer *LbVirtualServer `json:"virtual_server"`
}
