/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type FirewallRuleList struct {
	// List of firewall rules in the section. Only homogenous rules are supported.
	Rules []FirewallRule `json:"rules"`
}
