/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// NS Attributes data holder structure
type NsAttributes struct {
	// Reference to sub attributes for the attribute
	SubAttributes []NsAttributesData `json:"sub_attributes,omitempty"`
	// Data for attribute
	AttributesData *NsAttributesData `json:"attributes_data"`
}
