/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type FirewallSectionLock struct {
	// Comments for section lock/unlock.
	Comments string `json:"comments"`
	// Revision of the section.
	SectionRevision int64 `json:"section_revision"`
}
