/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type EdgeNodeDeploymentConfig struct {
	// Username and password settings for the node. Note - these settings will be honored only during node deployment. Post deployment, CLI must be used for changing the user settings, changes to these parameters will not have any effect. 
	NodeUserSettings *NodeUserSettings `json:"node_user_settings"`
	VmDeploymentConfig *DeploymentConfig `json:"vm_deployment_config"`
	// Supported edge form factor.
	FormFactor string `json:"form_factor,omitempty"`
}
