/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Contains info used to configure the VM on deployment
type ClusterNodeVmDeploymentConfig struct {
	// Specifies the config for the platform through which to deploy the VM 
	PlacementType string `json:"placement_type"`
}
