/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type TransportNodeStatus struct {
	// Roll-up status of pNIC, management connection, control connection, tunnel status, agent status
	Status string `json:"status,omitempty"`
	// Threat status
	ThreatStatus *ThreatStatus `json:"threat_status,omitempty"`
	// NSX agents status
	AgentStatus *AgentStatusCount `json:"agent_status,omitempty"`
	// Transport node uuid
	NodeUuid string `json:"node_uuid,omitempty"`
	// Tunnel Status
	TunnelStatus *TunnelStatusCount `json:"tunnel_status,omitempty"`
	// Management connection status
	MgmtConnectionStatus string `json:"mgmt_connection_status,omitempty"`
	// Control connection status
	ControlConnectionStatus *StatusCount `json:"control_connection_status,omitempty"`
	// pNIC status
	PnicStatus *StatusCount `json:"pnic_status,omitempty"`
	// Node status
	NodeStatus *NodeStatus `json:"node_status,omitempty"`
	// Transport node display name
	NodeDisplayName string `json:"node_display_name,omitempty"`
}
