/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Contains the deployment information for a cluster node VM soon to be deployed or already deployed by the Manager 
type ClusterNodeVmDeploymentRequest struct {
	// Info needed to configure a cluster node VM at deployment for a specific platform. May require different parameters depending on the method used to deploy the VM. 
	DeploymentConfig *ClusterNodeVmDeploymentConfig `json:"deployment_config"`
	// ID of the VM maintained internally and used to recognize it. Note: This is automatically generated and cannot be modified. 
	VmId string `json:"vm_id,omitempty"`
	// Username and password settings for the cluster node VM. Passwords must be at least 12 characters in length and contain at least one lowercase, one uppercase, one numerical, and one special character. Note: These settings will be honored only during VM deployment. Post-deployment, CLI must be used for changing the user settings and changes to these parameters will not have any effect. 
	UserSettings *NodeUserSettings `json:"user_settings,omitempty"`
	// List of cluster node role (or roles) which the VM should take on. They specify what type (or types) of cluster node which the new VM should act as. Currently both CONTROLLER and MANAGER must be provided, since this permutation is the only one supported now. 
	Roles []string `json:"roles"`
	// Specifies the desired \"size\" of the VM 
	FormFactor string `json:"form_factor,omitempty"`
}
