/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type VirtualMachineTagUpdate struct {
	// External id of the virtual machine to which tags are to be applied
	ExternalId string `json:"external_id"`
	// List of tags to be applied to the virtual machine
	Tags []Tag `json:"tags"`
}
