/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BGP routes per transport node.
type RoutesPerTransportNode struct {
	// Array of BGP neighbor route details for this transport node. 
	Routes []RouteDetails `json:"routes,omitempty"`
	// BGP neighbor source address.
	SourceAddress string `json:"source_address,omitempty"`
	// Transport node id
	TransportNodeId string `json:"transport_node_id,omitempty"`
}
