/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Match sequence in route map which is used for matching routes. IP prefix lists and match community expression are mutually exclusive fields, one of them must be provided. 
type RouteMapSequenceMatch struct {
	// It supports conjunction operator (AND) and five operators within singular community match expression (MATCH_ANY, MATCH_ALL, MATCH_EXACT, MATCH_NONE, MATCH_REGEX). 
	MatchCommunityExpression *CommunityMatchExpression `json:"match_community_expression,omitempty"`
	// IPPrefixList Identifiers for RouteMap Sequence Match Criteria
	IpPrefixLists []string `json:"ip_prefix_lists,omitempty"`
}
