/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ClustersAggregateInfo struct {
	// Array of Management Nodes
	ManagementCluster []ManagementNodeAggregateInfo `json:"management_cluster"`
	// Array of Controller Nodes
	ControllerCluster []ControllerNodeAggregateInfo `json:"controller_cluster"`
	// Status of all the cluster groups
	ClusterStatus *AllClusterGroupStatus `json:"cluster_status,omitempty"`
}
