/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type InitiateClusterRestoreRequest struct {
	// Timestamp of the backed-up configuration from which the appliance will be restored 
	Timestamp int64 `json:"timestamp,omitempty"`
	// Unique id of the backed-up configuration from which the appliance will be restored 
	NodeId string `json:"node_id,omitempty"`
	// IP address or FQDN of the node from which the backup was taken
	IpAddress string `json:"ip_address,omitempty"`
}
