/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Logical port attachment
type LogicalPortAttachment struct {
	// Indicates the type of logical port attachment. By default it is Virtual Machine interface (VIF)
	AttachmentType string `json:"attachment_type,omitempty"`
	// Extra context data for the attachment
	Context *AttachmentContext `json:"context,omitempty"`
	// Identifier of the interface attached to the logical port
	Id string `json:"id"`
}
