/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type Traceflow struct {
	// Link to this resource
	Self *SelfResourceLink `json:"_self,omitempty"`
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	// Represents the traceflow operation state
	OperationState string `json:"operation_state,omitempty"`
	// counters of observations from logical components
	LogicalCounters *TraceflowObservationCounters `json:"logical_counters,omitempty"`
	// Maximum time (in ms) the management plane will be waiting for this traceflow round.
	Timeout int64 `json:"timeout,omitempty"`
	// A flag, when set true, indicates some observations were deleted from the result set.
	ResultOverflowed bool `json:"result_overflowed,omitempty"`
	// id of the source logical port used for injecting the traceflow packet
	LportId string `json:"lport_id,omitempty"`
	// observation counters
	Counters *TraceflowObservationCounters `json:"counters,omitempty"`
	// The status of the traceflow RPC request. SUCCESS - The traceflow request is sent successfully. TIMEOUT - The traceflow request gets timeout. SOURCE_PORT_NOT_FOUND - The source port of the request cannot be found. DATA_PATH_NOT_READY - The datapath component cannot be ready to receive request. CONNECTION_ERROR - There is connection error on datapath component. UNKNOWN - The status of traceflow request cannot be determined.
	RequestStatus string `json:"request_status,omitempty"`
	// Traceflow result analysis notes
	Analysis []string `json:"analysis,omitempty"`
	// The id of the traceflow round
	Id string `json:"id,omitempty"`
}
