/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LbPersistenceCookieTime struct {
	// Both session cookie and persistence cookie are supported, Use LbSessionCookieTime for session cookie time setting, Use LbPersistenceCookieTime for persistence cookie time setting 
	Type_ string `json:"type"`
	// HTTP cookie max-age to expire cookie, only available for insert mode. 
	CookieMaxIdle int64 `json:"cookie_max_idle"`
}
