/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Configuration where backup files are stored for restore
type RestoreConfiguration struct {
	// The server from which backup files will be retrieved for restore.
	RemoteFileServer *RemoteFileServer `json:"remote_file_server"`
	// Passphrase used to encrypt backup files.
	Passphrase string `json:"passphrase,omitempty"`
}
