/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type UpgradeUnitGroupInfo struct {
	// Name of the group
	DisplayName string `json:"display_name,omitempty"`
	// Identifier of group
	Id string `json:"id,omitempty"`
}
