/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IPSec VPN policy traffic statistics
type IpSecVpnPolicyTrafficStatistics struct {
	// Aggregate traffic statistics across all ipsec tunnels.
	AggregateTrafficCounters *IpSecVpnTrafficCounters `json:"aggregate_traffic_counters,omitempty"`
	// Tunnel statistics.
	TunnelStatistics []IpSecVpnTunnelTrafficStatistics `json:"tunnel_statistics,omitempty"`
	// Tunnel port identifier.
	TunnelPortId string `json:"tunnel_port_id,omitempty"`
	// Policy Identifier.
	PolicyId string `json:"policy_id,omitempty"`
}
