/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Get the peer_code for each tunnel to paste on the remote end of the tunnel. Currently only stand-along/unmanaged edge is supported on the remote end of the tunnel.
type L2VpnSessionPeerCodes struct {
	// List of peer codes per transport tunnel.
	PeerCodes []L2VpnTunnelPeerCode `json:"peer_codes"`
}
