/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type NodeCertificateInfo struct {
	// SHA256 of certificate
	CertificateSha256Thumbprint string `json:"certificate_sha256_thumbprint,omitempty"`
	// Certificate content
	Certificate string `json:"certificate,omitempty"`
	// Entity type of this certificate
	EntityType string `json:"entity_type,omitempty"`
}
