/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type EdgeClusterMemberStatus struct {
	// Transport node backed by an Edge node.
	TransportNode *ResourceReference `json:"transport_node"`
	// Status of an edge node
	Status string `json:"status"`
}
