/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Transport Node State
type TransportNodeState struct {
	// Gives details of state of desired configuration. Please note, failed state is deprecated. Additional enums with more details on progress/success/ error states are sent for edge node. The success states are NODE_READY and TRANSPORT_NODE_READY, pending states are {VM_DEPLOYMENT_QUEUED, VM_DEPLOYMENT_IN_PROGRESS, REGISTRATION_PENDING} and other values indicate failures.
	State string `json:"state,omitempty"`
	// Array of configuration state of various sub systems
	Details []ConfigurationStateElement `json:"details,omitempty"`
	// Error code
	FailureCode int64 `json:"failure_code,omitempty"`
	// Error message in case of failure
	FailureMessage string `json:"failure_message,omitempty"`
	// Deployment progress state of transport node realization
	DeploymentProgressState *TransportNodeDeploymentProgressState `json:"deployment_progress_state,omitempty"`
	// Deployment status of installation
	NodeDeploymentState *ConfigurationState `json:"node_deployment_state,omitempty"`
	// States of HostSwitches on the host
	HostSwitchStates []HostSwitchState `json:"host_switch_states,omitempty"`
	// the present realized maintenance mode state
	MaintenanceModeState string `json:"maintenance_mode_state,omitempty"`
	// Unique Id of the TransportNode
	TransportNodeId string `json:"transport_node_id,omitempty"`
}
