/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Appliance registration access token
type RegistrationToken struct {
	// Access token
	Token string `json:"token"`
	// User delegated by token
	User string `json:"user,omitempty"`
	// List results
	Roles []string `json:"roles"`
}
