/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CapacityUsageMetaInfo struct {
	// Indicates the maximum global threshold percentage 
	MaxGlobalThresholdPercentage float32 `json:"max_global_threshold_percentage"`
	// Indicates the minimum global threshold percentage 
	MinGlobalThresholdPercentage float32 `json:"min_global_threshold_percentage"`
	// Timestamp at which capacity usage was last calculated
	LastUpdatedTimestamp int64 `json:"last_updated_timestamp"`
}
