/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// TLS protocol version
type ProtocolVersion struct {
	// Enable status for this protocol version
	Enabled bool `json:"enabled"`
	// Name of the TLS protocol version
	Name string `json:"name"`
}
