/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// NSGroupInfo contains information about a particular NSGroup used in a SI Rule. It also contains information about policy path used to create this NSGroup.
type NsGroupInfo struct {
	// Relative Policy path of a particular NSGroup.
	NsgroupPolicyPath string `json:"nsgroup_policy_path,omitempty"`
	// NSGroup Data.
	Nsgroup *ResourceReference `json:"nsgroup,omitempty"`
}
