/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type SupportBundleFileTransferProtocol struct {
	// SSH fingerprint of server
	SshFingerprint string `json:"ssh_fingerprint"`
	// Protocol name
	Name string `json:"name"`
	// Scheme to authenticate if required
	AuthenticationScheme *SupportBundleFileTransferAuthenticationScheme `json:"authentication_scheme"`
}
