/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Domain synchronization settings
type DirectoryDomainSyncSettings struct {
	// Directory domain full synchronization schedule using cron expression. For example, cron expression \"0 0 12 ? * SUN *\" means full sync is scheduled every Sunday midnight. If this object is null, it means there is no background cron job running for full sync.
	FullSyncCronExpr string `json:"full_sync_cron_expr,omitempty"`
	// Directory domain delta synchronization interval time between two delta sync in minutes.
	DeltaSyncInterval int64 `json:"delta_sync_interval,omitempty"`
}
