/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Match condition for client certficate issuer DN
type LbClientCertificateIssuerDnCondition struct {
	// If true, case is significant when comparing issuer DN value. 
	CaseSensitive bool `json:"case_sensitive,omitempty"`
	// Match type of issuer DN
	MatchType string `json:"match_type,omitempty"`
	// Value of issuer DN
	IssuerDn string `json:"issuer_dn"`
}
