/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type HttpsProtocol struct {
	// Protocol name
	Name string `json:"name"`
	// SSL thumbprint of server
	Sha256Thumbprint string `json:"sha256_thumbprint"`
	// Scheme to authenticate if required
	AuthenticationScheme *BasicAuthenticationScheme `json:"authentication_scheme,omitempty"`
}
