/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ManagementClusterNodeStatus struct {
	// Status of this node's connection to the management cluster
	MgmtClusterStatus string `json:"mgmt_cluster_status,omitempty"`
}
