/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MigrationSummary struct {
	// Target system version
	TargetVersion string `json:"target_version,omitempty"`
	// Status of migration
	MigrationStatus string `json:"migration_status,omitempty"`
	// Current version of migration coordinator
	MigrationCoordinatorVersion string `json:"migration_coordinator_version,omitempty"`
	// Current system version
	SystemVersion string `json:"system_version,omitempty"`
	ComponentTargetVersions []ComponentTargetVersion `json:"component_target_versions,omitempty"`
}
