/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type VerifiableAsymmetricLoginCredential struct {
	// Possible values are 'UsernamePasswordLoginCredential', 'VerifiableAsymmetricLoginCredential'.
	CredentialType string `json:"credential_type"`
	// Asymmetric login credential
	AsymmetricCredential string `json:"asymmetric_credential,omitempty"`
	// Credential verifier
	CredentialVerifier string `json:"credential_verifier,omitempty"`
	// Credential key
	CredentialKey string `json:"credential_key,omitempty"`
}
