/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type IcmpEchoRequestHeader struct {
	// ICMP id
	Id int64 `json:"id,omitempty"`
	// ICMP sequence number
	Sequence int64 `json:"sequence,omitempty"`
}
