/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Note- transport node templates APIs are deprecated and user is recommended to use transport node profiles APIs instead.
type NetworkMigrationSpecTypeIdEntry struct {
	// the id of the NetworkMigrationSpec
	Value string `json:"value"`
	// the type of the NetworkMigrationSpec
	Key string `json:"key,omitempty"`
}
