/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Community match expression
type CommunityMatchExpression struct {
	// Operator for evaluating community match expressions. AND logical AND operator 
	Operator string `json:"operator,omitempty"`
	// Array of community match operations
	Expression []CommunityMatchOperation `json:"expression"`
}
