/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Feature Permission
type FeaturePermission struct {
	// Feature Name
	Feature string `json:"feature,omitempty"`
	// Permission
	Permission string `json:"permission,omitempty"`
}
