/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// A login credential specifying a username and password
type UsernamePasswordLoginCredential struct {
	// Possible values are 'UsernamePasswordLoginCredential', 'VerifiableAsymmetricLoginCredential'.
	CredentialType string `json:"credential_type"`
	// The username for login
	Username string `json:"username,omitempty"`
	// The authentication password for login
	Password string `json:"password,omitempty"`
	// Thumbprint of the login server
	Thumbprint string `json:"thumbprint,omitempty"`
}
