/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LogicalPortMirrorDestination struct {
	// Resource types of mirror destination
	ResourceType string `json:"resource_type"`
	// Destination logical port identifier list.
	PortIds []string `json:"port_ids"`
}
