/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PendingChange struct {
	// Request identifier of the API which modified the entity.
	RequestId string `json:"request_id,omitempty"`
}
