/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AppInfoHostVmCsvRecord struct {
	// vm ids that this application belongs to
	HostVms string `json:"host_vms,omitempty"`
	// Version of the app
	Version string `json:"version,omitempty"`
	// Name of the app
	DisplayName string `json:"display_name,omitempty"`
	// OS type of the VM
	OsType string `json:"os_type,omitempty"`
	// Id of the app
	Id string `json:"id,omitempty"`
	// Manufacturer of the app
	Manufacturer string `json:"manufacturer,omitempty"`
}
