/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MessagingClientInfo struct {
	// Type of messaging client
	ClientType string `json:"client_type,omitempty"`
	// Account name in messaging client
	AccountName string `json:"account_name,omitempty"`
}
