/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Details of the instructions displayed during restore process
type InstructionInfo struct {
	// A list of fields that are displayable to users in a table
	Fields []string `json:"fields,omitempty"`
	// UUID of the instruction
	Id string `json:"id,omitempty"`
	// A list of actions that are to be applied to resources
	Actions []string `json:"actions,omitempty"`
	// Instruction name
	Name string `json:"name,omitempty"`
}
