/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CryptoAlgorithm struct {
	// supported key sizes for the algorithm
	KeySize []int64 `json:"key_size,omitempty"`
	// crypto algorithm name
	Name string `json:"name,omitempty"`
}
