/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// This action is used to create a new variable and assign value to it. One action can be used to create one variable. To create multiple variables, multiple actions must be defined. The variables can be used by LbVariableCondition, etc. 
type LbVariableAssignmentAction struct {
	// The property identifies the load balancer rule action type. 
	Type_ string `json:"type"`
	// Value of variable
	VariableValue string `json:"variable_value"`
	// Name of the variable to be assigned
	VariableName string `json:"variable_name"`
}
