/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Network interface properties of discovered node
type DiscoveredNodeInterfaceProperties struct {
	// Mac address of the interface
	PhysicalAddress string `json:"physical_address,omitempty"`
	// Switch name which is connected to nic, switch can be opaque, proxyHostSwitch or virtual
	ConnectedSwitch string `json:"connected_switch,omitempty"`
	// Id of the network interface
	InterfaceId string `json:"interface_id,omitempty"`
}
