/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type FirewallStatsList struct {
	// Total count for firewall rule statistics in results set
	ResultCount int64 `json:"result_count,omitempty"`
	// Corresponding firewall section identifier for list of rule statistics
	SectionId string `json:"section_id,omitempty"`
	// List of rule statistics
	Results []FirewallStats `json:"results,omitempty"`
}
