/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type NodeEntityInfo struct {
	// IP address of service provider
	IpAddress string `json:"ip_address,omitempty"`
	// Port number of service provider
	Port int64 `json:"port,omitempty"`
	// Entity type of this service endpoint
	EntityType string `json:"entity_type,omitempty"`
}
