/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// IP assignment specification for Static IP Pool.
type StaticIpPoolSpec struct {
	ResourceType string `json:"resource_type"`
	IpPoolId string `json:"ip_pool_id"`
}
