/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Collection of all registered ErrorResolverInfo
type ErrorResolverInfoList struct {
	// ErrorResolverInfo list
	Results []ErrorResolverInfo `json:"results"`
}
