/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Details about source and destination NSX setup to be migrated
type MigrationSetupInfo struct {
	// IP address or hostname of the destination NSX API endpoint.
	DestinationNsx *DestinationNsxApiEndpoint `json:"destination_nsx,omitempty"`
	// List of source NSX manager endpoints.
	SourceNsx []SourceNsxApiEndpoint `json:"source_nsx,omitempty"`
	// Migration mode can be VMC_V2T, ONPREMISE_V2T, ONPREMISE_VSPHERE2T
	MigrationMode string `json:"migration_mode,omitempty"`
}
