/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Host Switch State
type HostSwitchState struct {
	// External ID of the HostSwitch
	HostSwitchId string `json:"host_switch_id,omitempty"`
	// List of virtual tunnel endpoints which are configured on this switch
	Endpoints []Endpoint `json:"endpoints,omitempty"`
	// List of Ids of TransportZones this HostSwitch belongs to
	TransportZoneIds []string `json:"transport_zone_ids,omitempty"`
	// The name must be unique among all host switches specified in a given Transport Node.
	HostSwitchName string `json:"host_switch_name,omitempty"`
}
