/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type IpAddresses struct {
	// The IP addresses in the form of IP Address, IP Range, CIDR, used as source IPs or destination IPs of filters.
	IpAddresses []string `json:"ip_addresses,omitempty"`
}
