/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type SwitchingProfileStatus struct {
	// Number of logical ports using a switching profile
	NumLogicalPorts int64 `json:"num_logical_ports,omitempty"`
	// Identifier for the switching profile
	SwitchingProfileId string `json:"switching_profile_id,omitempty"`
	// Number of logical switches using a switching profile
	NumLogicalSwitches int64 `json:"num_logical_switches,omitempty"`
}
