/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Request Type to get a CRL's PEM file.
type CrlPemRequestType struct {
	// CRL Distribution Point URI where to fetch the CRL.
	CdpUri string `json:"cdp_uri,omitempty"`
}
