/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// The option is used to filter data on given node.
type PacketCaptureOption struct {
	// The avaiable option names in the enum can be used to filter the capture data.
	Name string `json:"name,omitempty"`
	// Define the capture value according to the given capture option.
	Value string `json:"value,omitempty"`
}
