/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ControlConnStatus struct {
	// Status of the control Node for e.g  UP, DOWN.
	Status string `json:"status,omitempty"`
	// IP address of the control Node.
	ControlNodeIp string `json:"control_node_ip,omitempty"`
	// Failure status of the control Node for e.g CONNECTION_REFUSED,INCOMPLETE_HOST_CERT.
	FailureStatus string `json:"failure_status,omitempty"`
}
