/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Node network interface alias
type NodeInterfaceAlias struct {
	// Interface configuration
	IpConfiguration string `json:"ip_configuration,omitempty"`
	// Interface netmask
	Netmask string `json:"netmask,omitempty"`
	// Interface IP address
	IpAddress string `json:"ip_address,omitempty"`
	// Interface MAC address
	PhysicalAddress string `json:"physical_address,omitempty"`
	// Interface broadcast address
	BroadcastAddress string `json:"broadcast_address,omitempty"`
}
