/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type SiAggregatedDataCounter struct {
	TxBytes *SiDataCounter `json:"tx_bytes,omitempty"`
	RxPackets *SiDataCounter `json:"rx_packets,omitempty"`
	TxPackets *SiDataCounter `json:"tx_packets,omitempty"`
	RxBytes *SiDataCounter `json:"rx_bytes,omitempty"`
}
