/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LbPoolMemberStatus struct {
	// UP means that pool member is enabled and monitors have marked the pool member as UP. If the pool member has no monitor configured, it would be treated as UP. DOWN means that pool member is enabled and monitors have marked the pool member as DOWN. DISABLED means that admin state of pool member is set to DISABLED. GRACEFUL_DISABLED means that admin state of pool member is set to GRACEFUL_DISABLED. UNUSED means that the pool member is not used when the IP list size of member group exceeds the maximum setting. The remaining IP addresses would not be used as available backend servers, hence mark the status as UNUSED. 
	Status string `json:"status"`
	// The healthcheck failure cause when status is DOWN
	FailureCause string `json:"failure_cause,omitempty"`
	// Timestamp in milliseconds since epoch
	LastCheckTime int64 `json:"last_check_time,omitempty"`
	// Pool member IP address
	IpAddress string `json:"ip_address"`
	// Timestamp in milliseconds since epoch
	LastStateChangeTime int64 `json:"last_state_change_time,omitempty"`
	// The port is configured in pool member. For virtual server port range case, pool member port must be null. 
	Port string `json:"port,omitempty"`
}
