/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Contains a list of cluster node VM deployment requests and optionally a clustering configuration. 
type AddClusterNodeVmInfo struct {
	// Cluster node VM deployment requests to be deployed by the Manager. 
	DeploymentRequests []ClusterNodeVmDeploymentRequest `json:"deployment_requests"`
	// This property is deprecated since ClusteringConfig is no longer needed for auto-installation and will be ignored if provided. 
	ClusteringConfig *ClusteringConfig `json:"clustering_config,omitempty"`
}
