/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Standard host switch specification is used for NSX configured transport node.
type StandardHostSwitchSpec struct {
	ResourceType string `json:"resource_type"`
	// Transport Node host switches
	HostSwitches []StandardHostSwitch `json:"host_switches"`
}
