/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Upgrade Coordinator state properties
type UcStateProperties struct {
	// Flag for updating upgrade-coodinator state properties to database
	UpdateUcStateProperties bool `json:"update_uc_state_properties,omitempty"`
}
