/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Define DHCP options of the DHCP service.
type DhcpOptions struct {
	// DHCP option 121 to define classless static routes.
	Option121 *DhcpOption121 `json:"option121,omitempty"`
	// To define DHCP options other than option 121 in generic format.
	Others []GenericDhcpOption `json:"others,omitempty"`
}
