/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ManagementClusterRoleConfig struct {
	// Type of this role configuration
	Type_ string `json:"type,omitempty"`
	// The IP and port for the management cluster service on this node
	MgmtClusterListenAddr *ServiceEndpoint `json:"mgmt_cluster_listen_addr,omitempty"`
	MpaMsgClientInfo *MsgClientInfo `json:"mpa_msg_client_info,omitempty"`
	// The IP and port for the public API service on this node
	ApiListenAddr *ServiceEndpoint `json:"api_listen_addr,omitempty"`
	// The IP, port and certificate for connecting to appliance.
	ApplianceConnectionInfo *ServiceEndpoint `json:"appliance_connection_info,omitempty"`
	// The IP and port for the management plane service on this node
	MgmtPlaneListenAddr *ServiceEndpoint `json:"mgmt_plane_listen_addr,omitempty"`
}
