/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Session statistics gives aggregated statistics of all policies for all the tunnels.
type IpSecVpnSessionStatistics struct {
	// Traffic statistics for IPSec VPN IKE session. Note - Not supported in this release.
	IkeTrafficStatistics *IpSecVpnikeTrafficStatistics `json:"ike_traffic_statistics,omitempty"`
	// Display name of vpn session.
	DisplayName string `json:"display_name,omitempty"`
	// Gives aggregate traffic statistics across all ipsec tunnels and individual tunnel statistics.
	PolicyStatistics []IpSecVpnPolicyTrafficStatistics `json:"policy_statistics,omitempty"`
	// Partial statistics if true specifies that the statistics are only from active node.
	PartialStats bool `json:"partial_stats,omitempty"`
	// UUID of vpn session.
	IpsecVpnSessionId string `json:"ipsec_vpn_session_id,omitempty"`
	// Timestamp when the data was last updated.
	LastUpdateTimestamp int64 `json:"last_update_timestamp,omitempty"`
	// Status for IPSec VPN IKE session UP/DOWN and fail reason if IKE session is down.
	IkeStatus *IpSecVpnikeSessionStatus `json:"ike_status,omitempty"`
	// Aggregate traffic statistics across all ipsec tunnels.
	AggregateTrafficCounters *IpSecVpnTrafficCounters `json:"aggregate_traffic_counters,omitempty"`
}
