/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Cluster Certificate ID
type ClusterCertificateId struct {
	// Certificate ID
	CertificateId string `json:"certificate_id"`
}
