/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type UpgradeHistory struct {
	// Timestamp (in milliseconds since epoch) when the upgrade was performed
	Timestamp int64 `json:"timestamp"`
	// Version being upgraded to
	TargetVersion string `json:"target_version"`
	// Version before the upgrade started
	InitialVersion string `json:"initial_version"`
	// Status of the upgrade
	UpgradeStatus string `json:"upgrade_status"`
}
