/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type EdgeClusterMemberAllocationProfile struct {
	// Logical router allocation can be tracked for specific services and services may have their own hard limits and allocation sizes. For example load balancer pool should be specified if load balancer service will be attached to logical router. 
	AllocationPool *EdgeClusterMemberAllocationPool `json:"allocation_pool,omitempty"`
	// Flag to enable the auto-relocation of standby service router running on edge cluster and node associated with the logical router. Only dynamically allocated tier1 logical routers are considered for the relocation. 
	EnableStandbyRelocation bool `json:"enable_standby_relocation,omitempty"`
}
