/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MAC learning configuration
type MacLearningSpec struct {
	// The maximum number of MAC addresses that can be learned on this port
	Limit int32 `json:"limit,omitempty"`
	// Aging time in sec for learned MAC address
	AgingTime int32 `json:"aging_time,omitempty"`
	// Allowing source MAC address learning
	Enabled bool `json:"enabled"`
	// The policy after MAC Limit is exceeded
	LimitPolicy string `json:"limit_policy,omitempty"`
	// Allowing flooding for unlearned MAC for ingress traffic
	UnicastFloodingAllowed bool `json:"unicast_flooding_allowed,omitempty"`
}
