/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AddClusterNodeSpec struct {
	// External identifier of the node
	ExternalId string `json:"external_id,omitempty"`
	ControllerRoleConfig *AddControllerNodeSpec `json:"controller_role_config,omitempty"`
	// Display name for the node
	DisplayName string `json:"display_name,omitempty"`
	MgrRoleConfig *AddManagementNodeSpec `json:"mgr_role_config,omitempty"`
}
