/*
 * NSX-T Manager API
 *
 * VMware NSX-T Manager REST API
 *
 * API version: 2.5.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type IpfixCollector struct {
	// IP address for the IPFIX collector
	CollectorIpAddress string `json:"collector_ip_address"`
	// Port for the IPFIX collector
	CollectorPort int32 `json:"collector_port,omitempty"`
}
